# Generated by Django 4.2.5 on 2023-10-22 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0002_blog_comentario_delete_arma_delete_mapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['titulo', '-fecha']},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 22, 54, 54, 85855, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 22, 54, 54, 84853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCsgo.blog'),
        ),
    ]
