# Generated by Django 4.2.5 on 2023-10-22 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0003_delete_jugador_alter_blog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 23, 9, 9, 182120, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 23, 9, 9, 182120, tzinfo=datetime.timezone.utc)),
        ),
    ]
