# Generated by Django 4.2.5 on 2023-10-22 23:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0004_alter_blog_fecha_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCsgo.blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 23, 55, 33, 946801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default=2, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 22, 23, 55, 33, 946801, tzinfo=datetime.timezone.utc)),
        ),
    ]
