# Generated by Django 4.2.5 on 2023-10-23 01:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0005_comentario_comentario_alter_blog_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 1, 38, 49, 539405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='AppCsgo.blog'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 1, 38, 49, 540406, tzinfo=datetime.timezone.utc)),
        ),
    ]
