# Generated by Django 4.2.5 on 2023-10-23 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0006_alter_blog_fecha_alter_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 2, 5, 34, 717311, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 2, 5, 34, 718313, tzinfo=datetime.timezone.utc)),
        ),
    ]
