# Generated by Django 4.2.5 on 2023-10-23 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCsgo', '0007_alter_blog_fecha_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 2, 39, 25, 940914, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.TextField(default=datetime.datetime(2023, 10, 23, 2, 39, 25, 941914, tzinfo=datetime.timezone.utc)),
        ),
    ]
